name: check-runner

on:
  workflow_dispatch:

jobs:
  check-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Check docker
        run: |
          which docker
          snap list
          dpkg -S $(which docker)
          apt-cache show $(dpkg -S $(which docker) | cut -f 1 -d :)
