name: Merge Queue Tests

on:
  # Trigger the workflow every night at 2:00 AM UTC.
  schedule:
    - cron: '0 2 * * *'

  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:
  
  pull_request:
  # Allows be called by a merge queue
  merge_group:

jobs:
  test:
    env:
      PR_NUM: ${{ github.event.pull_request.number }}
      EV_NUM: ${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          
          echo -e "\n PR number-> $PR_NUM x ${{ env.PR_NUM }} \nEV number-> $EV_NUM x ${{ env.EV_NUM }}\n"

          echo -e "Testing\n"
